### ISSUE TITLE
Can be used for WGS？

### ISSUE THREAD

**Issue by BioLaoXu** [G100DKFZ/gene-is#2]
Hi,dear team 
gene-is is a powerful tools for virus integration detection,but my data id WGS，Can be used for WGS？

**Comment by G100DKFZ** [comment]
Hi xf78,
geneis is designed for PCR based (eg LAM-PCR) and capture methods (eg TES). I would not recommend it for WGS sequences but depends also on the usage.

**Comment by BioLaoXu** [comment]
thanks @G100DKFZ
